import Head from "next/head";
import Image from "next/image";
import { Heading, Text, SimpleGrid } from "@chakra-ui/react";
import styles from "../styles/Home.module.css";
import { FaCheckCircle } from "react-icons/fa";
import BoxPrice from "../components/BoxPrice";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading as="h1" fontSize="4xl">
          Our Top Module
        </Heading>
        <Text mb={5} fontSize="lg" color={"gray.500"}>
          Get the exclusive package
        </Text>
        <SimpleGrid
          display={{ base: "row", sm: "row", md: "flex" }}
          columns={{ base: 1, md: 3 }}
          justify="center"
          textAlign="center"
          m="auto"
          spacing={{ base: 8, md: 2, sm: 5, lg: 6 }}
        >
          <BoxPrice />
          <BoxPrice />
          <BoxPrice />
        </SimpleGrid>
      </main>

      <footer className={styles.footer}>
        <Text>Develop by Kishor KC</Text>
      </footer>
    </div>
  );
}
