import Head from "next/head";
import Image from "next/image";
import {
  Heading,
  List,
  ListIcon,
  ListItem,
  VStack,
  useColorModeValue,
  Stack,
  Box,
  Text,
  HStack,
  Button,
  SimpleGrid,
} from "@chakra-ui/react";
import styles from "../styles/Home.module.css";
import { FaCheckCircle } from "react-icons/fa";
import BoxPrice from "../components/BoxPrice";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading as="h1" fontSize="4xl">
          Our Top Module
        </Heading>
        <Text mb={5} fontSize="lg" color={"gray.500"}>
          Get the exclusive package
        </Text>
        <SimpleGrid
          direction={{ base: "row", md: "" }}
          columns={3}
          justify="center"
          textAlign="center"
          spacing={{ base: 4, lg: 10 }}
        >
          <BoxPrice />
          <BoxPrice />
          <BoxPrice />
        </SimpleGrid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}